### ISSUE TITLE
app update fails with `exit status 100` on fedora 40

### ISSUE THREAD

**Issue by DaRandomCube** [hkdb/app#13]
i've made sure that

- [x] there is no existing issue about the same topic
- [x] read the prerequisites

here is the showcase video

https://github.com/user-attachments/assets/ca5a1a89-4265-4531-bac4-a7163f9708c6

**Comment by hkdb** [comment]
Thanks for bringing this up. According to the dnf man page:

```
exit code will be 100 when there are updates available and a list of the updates will be printed, 0 if not and 1 if an error occurs.
```

So I guess what I need to do is to not throw an error if `dnf check-update` returns 100. Will get this fixed on the next release.

**Comment by hkdb** [comment]
[v0.20](https://github.com/hkdb/app/releases/tag/v0.20) should have fixed this.
