### ISSUE TITLE
Error when installing on m2 Mac

### ISSUE THREAD

**Issue by BenjaminBini** [hkdb/app#15]
Hi,

The install script fails on my m2 mac because it fails to recognize the proc architecture.

Output of install.sh:

```console
📦️ Installing:

_____  ______ ______
\__  \ \____ \____  \
 / __ \|  |_> >  |_> >
(____  /   __/|   __/
     \/|__|   |__|

🚀️ The Cross-Platform Package Management Assistant with Super Powers

🐧️ Detecting OS...

🍎️ MacOS
💻️ Detecting CPU arch...

🏰️: arm64

❌️ CPU Architecture not supported... Exiting...

=> Done.

```

This code is wrong:
```shell
CPUARCH=""
UNAMEM=$(uname -m)
echo -e "🏰️: $UNAMEM\n"

if [[ "$UNAMEM" == "x86_64" ]] || [[ "$UNAMEM" == "amd64" ]]; then
  CPUARCH="amd64"
elif [[ "$UNAMEM" == "arm" ]]; then
  CPUARCH="arm64"
else
  echo -e "❌️ CPU Architecture not supported... Exiting...\n"
  exit 1
fi
```

because MacOS returns arm64 for uname command:

```console
$ uname -m
arm64

```

**Comment by BenjaminBini** [comment]
It also fails with release download.
The URL is wrong, it contains "macos" instead of "darwin".

**Comment by BenjaminBini** [comment]
Definitely some additional bugs:

<img width="637" alt="image" src="https://github.com/user-attachments/assets/0a0b720b-291b-45b8-b5a1-f362162df3c0">

**Comment by hkdb** [comment]
Thanks for reporting this! I am a bit slammed with work in the next few weeks but will certainly find time to get this fixed as soon as I can.

**Comment by BenjaminBini** [comment]
I'll try to submit a PR if I have time in the next days 👍

**Comment by hkdb** [comment]
Got my hands on a m3 air to work on this. [v0.19](https://github.com/hkdb/app/releases/tag/v0.19) should fix this plus more...
